[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM10         ; ← поменяйте на свой порт
monitor_port = COM10

lib_deps = 
        ESP32Servo@^1.0.3