[env:esp32-s3-devkitc-1]
platform = espressif32@~6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
lib_deps = 
    https://github.com/gilmaimon/ArduinoWebsockets.git
    arminjo/ServoEasing@^2.4.0
    ESP32Servo@^1.0.3